blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/JacobPEvans/.github/discussions
    about: For questions or open discussions, please use GitHub Discussions instead.
